### ISSUE TITLE
sci-eco_footer

### ISSUE THREAD

**Issue by prasannakumaar28** [sci-eco/sci-eco.github.io#7]
- footer to be designed in all pages
  - [x] home
  - [x] about
  - [ ] post

**Comment by suriyadeepan** [comment]
@prasannakumaar28 Shouldn't we have a common footer for all the pages?

**Comment by prasannakumaar28** [comment]
Ya its common footer, the one in the site is fair enough!

**Comment by suriyadeepan** [comment]
Closing issue as resolved!
